Repository LLNL/maestrowf, pull requests merged in 2018-08, with the labels that each got.

#125 Updated exception messages
  maestrowf/conductor.py
  maestrowf/datastructures/core/study.py
  maestrowf/datastructures/yamlspecification.py
Labels: bug

#127 Fix status.csv 'State' column writeout.
  maestrowf/datastructures/core/executiongraph.py
Labels: Bugfix

#128 #107 Enhance/return codes
  maestrowf/abstracts/enums/__init__.py
  maestrowf/conductor.py
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/maestro.py
Labels: enhancement

#131 Bugfix that would cause the ExecutionGraph to not update when cancelled.
  maestrowf/datastructures/core/executiongraph.py
Labels: Bugfix

#130 Addition of Quick Start documentation.
  docs/source/index.rst
  docs/source/lulesh_breakdown.rst
  docs/source/maestro_core.rst
  docs/source/quick_start.rst
Labels: Documentation

#129 Addition of custom parameter generation when running studies.
  maestrowf/datastructures/core/parameters.py
  maestrowf/datastructures/core/study.py
  maestrowf/maestro.py
  samples/parameterization/custom_generator.py
  samples/parameterization/lulesh_custom_gen.py
Labels: Feature

#132 Addition of a LULESH study specification with heavier comments.
  samples/documentation/lulesh_sample1_unix_commented.yaml
Labels: Documentation, In Progress

#137 More flexible ExecutionGraph description API and logging of description.
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/datastructures/core/study.py
Labels: Bugfix, enhancement

#138 Fix to Variable verification.
  maestrowf/datastructures/environment/variable.py
Labels: Bugfix

#114 Updates to Maestro documentation
  README.md
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/lulesh_breakdown.rst
  docs/source/maestro_core.rst
  docs/source/quick_start.rst
  samples/documentation/lulesh_sample1_unix_commented.yaml
Labels: Documentation, In Progress

#136 Throttled workflows push steps into the ready queue multiple times.
  maestrowf/datastructures/core/executiongraph.py
Labels: Bugfix
