Repository LLNL/maestrowf, pull requests merged in 2018-07, with the labels that each got.

#115 Sphinx Documentation
  docs/source/getting_started.rst
  docs/source/index.rst
Labels: Discussion, Documentation

#116 Flux for Spectrum bugfixes
  maestrowf/interfaces/script/fluxscriptadapter.py
Labels: Bugfix

#119 Tweaks and addition of 'starting' state to SpectrumFluxAdapter.
  maestrowf/interfaces/script/fluxscriptadapter.py
Labels: Bugfix

#122 Additional debug logging for the Flux Spectrum Adapter
  maestrowf/interfaces/script/fluxscriptadapter.py
Labels: enhancement
