Repository LLNL/maestrowf, pull requests merged in 2018-04, with the labels that each got.

#85 Removal of the prepend assumption for remote launching.
  maestrowf/abstracts/interfaces/schedulerscriptadapter.py
Labels: Bugfix, enhancement

#86 Feature/restart attempts
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/maestro.py
Labels: Feature

#91 Read The Docs
  docs/README.md
  docs/source/conf.py
  docs/source/index.rst
  docs/source/maestrowf.abstracts.enums.rst
  docs/source/maestrowf.abstracts.interfaces.rst
  docs/source/maestrowf.abstracts.rst
  docs/source/maestrowf.datastructures.core.rst
  docs/source/maestrowf.datastructures.environment.rst
  docs/source/maestrowf.datastructures.rst
  docs/source/maestrowf.interfaces.rst
  docs/source/maestrowf.interfaces.script.rst
  docs/source/maestrowf.rst
  docs/source/modules.rst
  docs/source/setup.rst
  maestrowf/abstracts/envobject.py
  maestrowf/abstracts/interfaces/schedulerscriptadapter.py
  maestrowf/abstracts/interfaces/scriptadapter.py
  maestrowf/abstracts/specification.py
  maestrowf/datastructures/core/__init__.py
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/datastructures/core/parameters.py
  maestrowf/datastructures/core/study.py
  maestrowf/datastructures/core/studyenvironment.py
  maestrowf/datastructures/environment/gitdependency.py
  maestrowf/datastructures/environment/pathdependency.py
  maestrowf/datastructures/environment/variable.py
  maestrowf/datastructures/yamlspecification.py
  maestrowf/interfaces/script/localscriptadapter.py
  maestrowf/interfaces/script/slurmscriptadapter.py
  maestrowf/maestro.py
  maestrowf/utils.py
Labels: Documentation

#92 Adds the ability to generate scripts as needed (and tmp dir support)
  maestrowf/conductor.py
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/datastructures/core/study.py
  maestrowf/maestro.py
  samples/lulesh/lulesh_sample1_macosx.yaml
  samples/lulesh/lulesh_sample1_unix.yaml
Labels: enhancement
