Repository LLNL/maestrowf, pull requests merged in 2018-05, with the labels that each got.

#94 Add the ability to specify cores per task for SLURM
  maestrowf/interfaces/script/slurmscriptadapter.py
Labels: enhancement

#82 Flux adapter (Spectrum MPI)
  maestrowf/abstracts/interfaces/schedulerscriptadapter.py
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/datastructures/core/study.py
  maestrowf/interfaces/__init__.py
  maestrowf/interfaces/script/__init__.py
  maestrowf/interfaces/script/fluxscriptadapter.py
Labels: In Progress, enhancement

#97 Correction of how dependency ordering happens during study construction.
  maestrowf/abstracts/interfaces/schedulerscriptadapter.py
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/datastructures/core/study.py
  maestrowf/datastructures/dag.py
  maestrowf/interfaces/script/slurmscriptadapter.py
  maestrowf/maestro.py
  maestrowf/utils.py
  samples/lulesh/lulesh_sample1_macosx.yaml
  samples/lulesh/lulesh_sample1_unix.yaml
Labels: Bugfix, Needs Review, enhancement

#103 Correct the inability of accessing the study output root directory.
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/datastructures/core/study.py
  maestrowf/datastructures/core/studyenvironment.py
  maestrowf/maestro.py
  samples/lulesh/lulesh_sample1_macosx.yaml
  samples/lulesh/lulesh_sample1_unix.yaml
Labels: Bugfix, enhancement
