Repository LLNL/maestrowf, pull requests merged in 2018-11, with the labels that each got.

#157 Correction to safe pathing for missed cases and make_safe_path enhancements.
  maestrowf/datastructures/core/study.py
  maestrowf/maestro.py
  maestrowf/utils.py
Labels: Bugfix, Needs Review, enhancement

#160 Correction to fix the format of output status time to avoid a comma that breaks printing.
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/utils.py
Labels: Bugfix, Confirmed, Needs Review

#156 Removal of _stage_linear since it is now not needed.
  maestrowf/datastructures/core/study.py
  samples/lulesh/lulesh_sample1_macosx_linear.yaml
  samples/lulesh/lulesh_sample1_unix_linear.yaml
  setup.py
Labels: Bugfix, Confirmed, Needs Review

#152 Addition of pargs for passing parameters to custom parameter generation
  maestrowf/maestro.py
  maestrowf/utils.py
  samples/parameterization/lulesh_montecarlo_args.py
  setup.py
Labels: enhancement

#162 do not overwrite log file in the lulesh unix example
  samples/lulesh/lulesh_sample1_unix.yaml
Labels: Documentation, bug
