Repository LLNL/maestrowf, pull requests merged in 2018-10, with the labels that each got.

#149 More generalized FluxScriptAdapter
  maestrowf/interfaces/__init__.py
  maestrowf/interfaces/script/__init__.py
  maestrowf/interfaces/script/fluxscriptadapter.py
Labels: Adapters, Feature, In Progress

#139 README tweak to update quickstart link.
  README.md
Labels: Documentation, In Progress

#154 typos. fixes #141
  maestrowf/datastructures/core/executiongraph.py
Labels: Bugfix
