Repository LLNL/maestrowf, pull requests merged in 2019-03, with the labels that each got.

#172 PyYAML vulnerability fix - also in requirements.txt
  requirements.txt
Labels: Bugfix, High Priority

#174 Addition of a loader to the yaml load call.
  maestrowf/datastructures/yamlspecification.py
Labels: Bugfix

#176 Correction to install enum34 for Python versions < 3.4
  requirements.txt
  setup.py
Labels: Infrastructure

#178 Addition of a Dockerfile for tutorials and ease of trying out.
  Dockerfile
  docs/source/getting_started.rst
Labels: Documentation, Infrastructure
