Repository LLNL/maestrowf, pull requests merged in 2020-09, with the labels that each got.

#312 Updated the Dockerfile and documentation
  Dockerfile
  docs/source/installing.rst
Labels: Documentation

#315 Removal of Python 2.7 and addition of newer Python 3 versions
  .travis.yml
  tox.ini
Labels: Infrastructure, TravisCI

#319 simple bug fix in the YAMLSpec description setter
  maestrowf/specification/yamlspecification.py
Labels: Bugfix, Specification

#316 Conversion to Poetry Build System
  .coveragerc
  .pre-commit-config.yaml
  .travis.yml
  Pipfile
  README.md
  poetry.lock
  pyproject.toml
  pytest.ini
  requirements.txt
  setup.cfg
  setup.py
  tox.ini
Labels: Infrastructure, TravisCI

#317 YAMLSpecification Testing
  .gitignore
  maestrowf/specification/schemas/yamlspecification.json
  pyproject.toml
  pytest.ini
  tests/conftest.py
  tests/specification/__init__.py
  tests/specification/test_specs/duplicate_dependency.yml
  tests/specification/test_specs/empty_output_path.yml
  tests/specification/test_specs/empty_variables.yml
  tests/specification/test_specs/error_parameterized.yml
  tests/specification/test_specs/extra_study_params.yml
  tests/specification/test_specs/hello_bye_parameterized.yml
  tests/specification/test_specs/hello_world.yml
  tests/specification/test_specs/lulesh_sample1_unix.yml
  tests/specification/test_specs/missing_step.yml
  tests/specification/test_specs/missing_step_desc.yml
  tests/specification/test_yaml_specification.py
  tox.ini
Labels: In Progress, Infrastructure, enhancement

#314 Add name and real_name StudyStep properties.
  maestrowf/abstracts/interfaces/scriptadapter.py
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/datastructures/core/study.py
  maestrowf/interfaces/script/fluxscriptadapter.py
  maestrowf/interfaces/script/localscriptadapter.py
  maestrowf/interfaces/script/lsfscriptadapter.py
  maestrowf/interfaces/script/slurmscriptadapter.py
Labels: Bugfix

#305 Slurm Script Adapter Bug Fix
  maestrowf/interfaces/script/slurmscriptadapter.py
Labels: Adapters, Bugfix, High Priority, In Progress
