Repository LLNL/maestrowf, pull requests merged in 2020-08, with the labels that each got.

#302 Bugfix: Division by string instead of number
  maestrowf/interfaces/script/lsfscriptadapter.py
Labels: Bugfix

#301 Addition of processing multiple directories and globs for status
  maestrowf/maestro.py
Labels: enhancement

#306 Updated the documentation to pull the recent version
  docs/source/conf.py
Labels: Documentation

#308 Updated the documentation for installing Maestro
  docs/source/index.rst
  docs/source/installing.rst
Labels: Documentation
