Repository LLNL/maestrowf, pull requests merged in 2020-04, with the labels that each got.

#241 Fix to add PID to local log names.
  maestrowf/interfaces/script/localscriptadapter.py
Labels: Bugfix

#242 Refactor to move DAG operations to the back end Conductor
  maestrowf/abstracts/__init__.py
  maestrowf/abstracts/envobject.py
  maestrowf/abstracts/graph.py
  maestrowf/abstracts/simobject.py
  maestrowf/abstracts/specification.py
  maestrowf/conductor.py
  maestrowf/datastructures/__init__.py
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/datastructures/core/parameters.py
  maestrowf/datastructures/core/study.py
  maestrowf/datastructures/core/studyenvironment.py
  maestrowf/datastructures/yamlspecification.py
  maestrowf/maestro.py
Labels: In Progress, Planning and Design, enhancement

#244 Pre-Commit Checks
  .pre-commit-config.yaml
  Pipfile
  requirements.txt
Labels: Infrastructure

#247 Bugfix for logging that didn't appear in submodules
  maestrowf/maestro.py
  maestrowf/utils.py
Labels: Bugfix, enhancement

#243 Added checks for invalid keys.
  MANIFEST.in
  maestrowf/datastructures/schemas.json
  maestrowf/datastructures/yamlspecification.py
  maestrowf/maestro.py
  requirements.txt
  setup.py
Labels: Specification, enhancement

#252 log improvements
  maestrowf/conductor.py
  maestrowf/datastructures/core/study.py
  maestrowf/datastructures/core/studyenvironment.py
  maestrowf/maestro.py
  maestrowf/utils.py
  requirements.txt
  setup.py
Labels: enhancement

#256 No "variables" bugfix
  maestrowf/datastructures/schemas.json
  maestrowf/datastructures/yamlspecification.py
Labels: Bugfix
