Repository LLNL/maestrowf, pull requests merged in 2020-05, with the labels that each got.

#259 Addition of a simple dry-run capability.
  maestrowf/abstracts/enums/__init__.py
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/datastructures/core/study.py
  maestrowf/maestro.py
Labels: Feature

#262 enabled raw sbatch errors to be logged
  maestrowf/interfaces/script/slurmscriptadapter.py
Labels: enhancement

#263 Tweaks and fixes to the SLURM header.
  maestrowf/datastructures/schemas.json
  maestrowf/interfaces/script/slurmscriptadapter.py
  requirements.txt
  samples/lulesh/lulesh_sample1_unix_slurm.yaml
  setup.py
Labels: Adapters, Bugfix, enhancement

#265 modified executiongraph to round datetimes to nearest second
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/utils.py
Labels: enhancement

#266 Adds a check for UNKNOWN state.
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/utils.py
Labels: Adapters, Bugfix

#269 Addition of README as long description.
  setup.py
Labels: Documentation, Release Process

#275 Pgen docs
  docs/source/index.rst
  docs/source/maestrowf.abstracts.rst
  docs/source/maestrowf.interfaces.script.rst
  docs/source/parameters.rst
  docs/source/pgen_images/cheb_map.png
  maestrowf/abstracts/envobject.py
  maestrowf/abstracts/specification.py
  maestrowf/conductor.py
  maestrowf/datastructures/yamlspecification.py
  maestrowf/interfaces/script/__init__.py
  maestrowf/interfaces/script/fluxscriptadapter.py
  maestrowf/interfaces/script/lsfscriptadapter.py
  samples/parameterization/custom_generator.py
  samples/parameterization/lulesh_custom_gen.py
  samples/parameterization/lulesh_itertools_pgen.py
  samples/parameterization/lulesh_montecarlo_args.py
  samples/parameterization/np_cheb_pgen_pargs.py
Labels: Documentation

#277 Replace unicode quote with ascii quote
  README.md
Labels: Bugfix

#278 Updated the docs release version to 1.1.7
  docs/source/conf.py
Labels: Documentation
