Repository LLNL/maestrowf, pull requests merged in 2020-10, with the labels that each got.

#323 WIP: Add job identifier to status command
  maestrowf/conductor.py
  maestrowf/datastructures/core/executiongraph.py
Labels: enhancement

#325 Fixes #324
  docs/source/installing.rst
  maestrowf/abstracts/__init__.py
  maestrowf/abstracts/abstractclassmethod.py
  maestrowf/abstracts/envobject.py
  maestrowf/abstracts/interfaces/schedulerscriptadapter.py
  maestrowf/conductor.py
  maestrowf/datastructures/core/parameters.py
  maestrowf/datastructures/core/study.py
  maestrowf/datastructures/dag.py
  maestrowf/datastructures/environment/gitdependency.py
  maestrowf/interfaces/script/__init__.py
  maestrowf/interfaces/script/slurmscriptadapter.py
  maestrowf/maestro.py
  samples/documentation/lulesh_sample1_unix_commented.yaml
  samples/parameterization/lulesh_itertools_pgen.py
  tests/interfaces/test_script_adapter.py
Labels: Documentation

#328 A fix to the GitDependency that prevents a timeout on repository status checking
  maestrowf/datastructures/environment/gitdependency.py
Labels: Bugfix
