Repository LLNL/maestrowf, pull requests merged in 2022-04, with the labels that each got.

#389 Add black to the pre-commit hooks for automatic styling.
  .pre-commit-config.yaml
Labels: Infrastructure

#384 Enable more complete configurability of jsrun launcher
  docs/source/index.rst
  docs/source/lulesh_breakdown.rst
  docs/source/schedulers.rst
  maestrowf/datastructures/core/executiongraph.py
  maestrowf/interfaces/script/lsfscriptadapter.py
  maestrowf/specification/schemas/yamlspecification.json
  maestrowf/specification/yamlspecification.py
  samples/lulesh/lulesh_sample1_unix_lsf.yaml
  tests/interfaces/script/test_lsfscriptadapter.py
Labels: Adapters

#392 Updating dependency versions for 1.1.9 release.
  poetry.lock
Labels: Release Process
