Repository LLNL/maestrowf, pull requests merged in 2023-08, with the labels that each got.

#426 Update lock file to new/safe certifi
  poetry.lock
Labels: Bugfix, dependencies

#420 feature/bgunnar5/status-pager
  docs/Maestro/cli.md
  docs/Maestro/monitoring.md
  docs/assets/images/examples/study_monitoring/status_inside_pager.png
  docs/assets/images/examples/study_monitoring/status_outside_pager.png
  docs/assets/images/examples/study_monitoring/status_theme_error.png
  docs/assets/images/examples/study_monitoring/status_with_disable_pager.png
  docs/assets/images/examples/study_monitoring/status_with_disable_theme.png
  docs/custom.css
  maestrowf/__init__.py
  maestrowf/maestro.py
  pyproject.toml
  tests/status/test_status_renderers.py
Labels: enhancement

#427 Add packaging as explicit dependency
  docs/Maestro/scheduling.md
  maestrowf/abstracts/interfaces/flux.py
  poetry.lock
  pyproject.toml
  tests/utils/test_utils.py
Labels: Bugfix
